export const dataStore = [
  {
    id: "ZslUoAbx2DADZDdO",
    user_id: "A775",
    title: "adadad",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "adadad",
    banner:
      "https://dg86kmop4ajn0.cloudfront.net/assets/2022/01/24/A775_5EwB3kH79Tb0VY5rJoRE2hMKV_1643008073069.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "5b4qkbZhqkxxriJC",
    user_id: "A775",
    title: "Baby_Baby",
    desc: "",
    domain_id: "tbqSKGhsbWi4XpIx",
    domain: "v2.tee86.com",
    seo_title: "Baby_Baby",
    seo_desc:
      "Baby_Baby makes it easier than ever to sell shirts you design, leveraging crowd funding and social media to help you sell your shirt and make money, all with absolutely no money down",
    seo_image_cover:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/12/25/A775_store_1c3cvhndsxwrv.jpg",
    fb_pixel: "",
    url: "babybaby",
    banner:
      "https://dg86kmop4ajn0.cloudfront.net/assets/2022/01/21/A775_VzgRwideBPUYBHA9CipFvn6nW_1642754636421.jpg",
    private: false,
    state: "inactive",
  },
  {
    id: "1D0y8fCShvj0kbc1",
    user_id: "A775",
    title: "Bunny",
    desc: "",
    domain_id: "tbqSKGhsbWi4XpIx",
    domain: "v2.tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "bunny",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/12/25/A775_store_ei7c8os5ngcjg.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "CpMryLAEvfIywGU1",
    user_id: "A775",
    title: "Lovely",
    desc: "",
    domain_id: "tbqSKGhsbWi4XpIx",
    domain: "v2.tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "lovely",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/12/25/A775_store_6226xggxwtu0d.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "csPIMb6NSjVbgDaU",
    user_id: "A775",
    title: "new store",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "new-store-307460",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "paipRbMpsuaUFTgZ",
    user_id: "A775",
    title: "Lam Luyen",
    desc: "",
    domain_id: "rxdPxaEbptMV_lMt",
    domain: "hungdt.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "lam-luyen",
    banner: "",
    private: true,
    state: "approved",
  },
  {
    id: "dD4Ia9ovd0DIDMxs",
    user_id: "A775",
    title: "store 2",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "store-2",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "C8KqeJVi9lHwtaWG",
    user_id: "A775",
    title: "store 1",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "store-1-450512",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "X16bxuvktvOITKkb",
    user_id: "A775",
    title: "test",
    desc: "<p>t</p>",
    domain_id: "nis4Cbc8VV623Qt8",
    domain: "hungdt.30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test-814825",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "bg1O2Bz2emdifeRj",
    user_id: "A775",
    title: "Test03062019tt",
    desc: "<p>tttt</p>",
    domain_id: "nis4Cbc8VV623Qt8",
    domain: "hungdt.30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test03062019tt",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "Brsbg9oSFlzblf1A",
    user_id: "A775",
    title: "Adidi",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "adidi",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "XEujQjYics9czjlX",
    user_id: "A775",
    title: "Abidas",
    desc: "<p>Abidas</p>",
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "abidas",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "7bGZLEqbfWbFWmjO",
    user_id: "A775",
    title: "Hung test",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "hung-test-611468",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "qCdG6zXzxlurx4Ta",
    user_id: "A775",
    title: "Puggie 3D Apparel",
    desc: "<p>Only available for a LIMITED TIME, so get yours TODAY!</p>",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "puggie-3d-apparel",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "T8Pj5W4kioFntbB2",
    user_id: "A775",
    title: "aaaaaaaaaaaaaaaaaaa",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "aaaaaaaaaaaaaaaaaaaaa",
    banner: "",
    private: false,
    state: "inactive",
  },
  {
    id: "L72u2EjOLYuAFdCW",
    user_id: "A775",
    title: "Thanks to our footprint we don't just build the BB",
    desc: '<p><span style="color: rgb(84, 84, 84);">Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;.. Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;..Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;..Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;..Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;..Thanks to our footprint we don\'t just build the&nbsp;</span><strong style="color: rgb(106, 106, 106);">BBC</strong><span style="color: rgb(84, 84, 84);">-brand internationally, we also support the wider UK creative economy, showcasing the best of British content&nbsp;..</span></p>',
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "thanks-to-our-footprint-we-dont-just-build-the-bb",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "HcxEtpx5SMTvA0zM",
    user_id: "A775",
    title: "BUNY_BUNY_BUNY  ",
    desc: '<p><img src="https://kenh14cdn.com/thumb_w/660/2019/8/6/shyn-11-15651056519271390662049.jpg"></p><p class="ql-align-center"><span style="color: rgb(34, 34, 34);">Đặc biệt, Á hậu Hoàng Thùy cũng là một trong những ứng viên nhận được sự quan tâm của cộng đồng fan sắc đẹp quốc tế. Trong danh sách những thí sinh tham gia Miss Universe 2019 có lượt theo dõi cao trên IG được chuyên trang sắc đẹp uy tín thế giới Missosology công bố, cập nhật đến ngày 30/07, Á hậu Hoàng Thùy xuất sắc đứng ở vị trí thứ 5, vượt qua nhiều thí sinh khác như đại diện Mỹ, Mexico, Puerto Rico.</span></p><p><br></p>',
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "wwwwwwwwwwwwwwwwwwwwww",
    banner: "",
    private: true,
    state: "approved",
  },
  {
    id: "MmwaYoTfR33WhD7v",
    user_id: "A775",
    title: "ta_da",
    desc: '<p><span style="color: rgb(68, 68, 68);" class="ql-size-large">以前人们在四月开始收获 - 躺在高高的谷堆上面笑着&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">我穿过 金黄的麦田 -去给 稻草人唱歌&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">等着 落山风吹过 -你从一座叫“我”的小镇经过&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">刚好屋顶的雪化成雨飘落 -你穿着 透明的衣服&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">给我 一个人唱歌 -全都是 我喜欢的歌&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">我们去大草原的湖边 -等候鸟飞回来&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">等我们都长大了就生一个娃娃 -他会自己长大远去&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">我们也各自远去 -我给你写信 你不会回信&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">就这 样吧 -说好了吧&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">去大草原的湖边 -等候鸟飞回来&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">等我们都长大了就生一个娃娃 - 他会自己长大远去&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">我们也各自远去 -我给你写信 你不要回信&nbsp;</span></p><p><span style="color: rgb(68, 68, 68);" class="ql-size-large">就这 样吧</span></p><p><br></p><p><br></p>',
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "tada",
    banner: "",
    private: true,
    state: "approved",
  },
  {
    id: "wAdKAPkRWR5mQuRd",
    user_id: "A775",
    title: "bunybuny",
    desc: '<ul><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Con cóc chẳng phải con gà</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Quả ổi chẳng phải quả na quả dừa</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Cái đục chẳng giống cái cưa</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Mùa xuân không thể có mưa mùa hè</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Đôi mắt không phải để nghe</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Đôi dép không phải để che trên đầu</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Đã nghèo thì không thể giàu</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Ngồi trên đỉnh núi không thể câu cá mè</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Mới đẻ sao biết đi xe</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Điếc tai sao có thể nghe nói thầm</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Đã đúng thì không thể nhầm</em></li><li class="ql-align-center"><em class="ql-size-large" style="color: rgb(230, 0, 0);">Cục than đang nóng không ai cầm vào</em></li></ul><p class="ql-align-center"><br></p><ul><li class="ql-align-center"><br></li></ul>',
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "bunybuny",
    banner: "",
    private: true,
    state: "approved",
  },
  {
    id: "1kwCIt4OaShNbkK4",
    user_id: "A775",
    title: "test 3 tets test",
    desc: "",
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test-3-tets-test",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "8fXMexaUtpVnEUps",
    user_id: "A775",
    title: "ALO123 loa 1",
    desc: "",
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "alo123-loa-1-loa2",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "lLAQ1fF8qww0xb8l",
    user_id: "A775",
    title: "Hakuna_matata",
    desc: '<p><img src="https://kenh14cdn.com/thumb_w/620/2019/8/7/hoang-thuy-8-15651573629881596797995.jpg">﻿BÉ HỌC CÚI CHÀO</p><p>Cây lúa càng trĩu bông</p><p>Cúi đầu càng khiêm tốn</p><p>Bé học tập cây lúa</p><p>Khiêm tốn để vươn cao&nbsp;</p><p>Gặp ai cũng cúi chào</p><p>Mọi người đều vui vẻ</p><p>Khi bé đến nhà trẻ</p><p>Trước: Cúi chào Thầy, Cô</p><p>Sau: Cúi chào các bạn</p><p>Khi bé về đến nhà</p><p>Trước: Cúi chào Ông, Bà</p><p>Sau: Cúi chào Mẹ, Cha</p><p>Cả nhà hân hoan quá!</p><p>Cúi chào là cung kính</p><p>Gặp người lớn hơn mình&nbsp;</p><p>Càng phải nên cung kính</p><p>Bé có tâm cung kính</p><p class="ql-align-justify">Được mọi người yêu thương!<img src="https://kenh14cdn.com/thumb_w/620/2019/8/7/hoang-thuy-10-15651573629931254175117.jpg"></p>',
    domain_id: "LLCiQXEY5I3wT1KF",
    domain: "30usd.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "hakunamatata",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/07/22/A775_store_ve84qkmu8xy3k.png",
    private: true,
    state: "approved",
  },
  {
    id: "RV5ssAz1ofm7YuUW",
    user_id: "A775",
    title: "DOREMON",
    desc: "<p><strong>Test content</strong></p>",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "doremon",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "WDKCs91hbcbbhHvt",
    user_id: "A775",
    title: "Siderman",
    desc: "<p>Test content</p>",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test-campv2-21",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/07/16/A775_store_xonbdistvfnnd.png",
    private: true,
    state: "approved",
  },
  {
    id: "13wMnQBA1knK4LeF",
    user_id: "A775",
    title: "hoahoong123(-_-)",
    desc: "<p><strong>Test content</strong></p>",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "hoahoong123(-_",
    seo_desc:
      "con cào cào có cái canh xanh xanh nó bay rất nhanh từ bụi cây sang bụi cỏ, con cào cào rất thích thể thao",
    seo_image_cover:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/07/03/A775_seo_img_ixwyrvcdluj4q.png",
    fb_pixel: "hgtygyhuyyh",
    url: "h-k-l-f",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/07/02/A775_store_cw1v82qeckn0d.png",
    private: false,
    state: "approved",
  },
  {
    id: "UzdogaaJ8GCeRlHP",
    user_id: "A775",
    title: "nana",
    desc: "%3Cp%3E%3Cstrong%20class%3D%22ql-size-large%22%20style%3D%22color%3A%20rgb(230%2C%200%2C%200)%3B%22%3E%3Cem%3E%3Cs%3E%3Cu%3Ehinhinhin%3C%2Fu%3E%3C%2Fs%3E%3C%2Fem%3E%3C%2Fstrong%3E%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "nana",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/07/01/A775_store_hdsldibl4bhbu.jpg",
    private: true,
    state: "approved",
  },
  {
    id: "k5WeAQc7Lisb8VET",
    user_id: "A775",
    title: "Test 001",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test-001",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "6aIrJ3oA5g7wkRb8",
    user_id: "A775",
    title: "Storefront1",
    desc: "%3Cp%3EStore%20desc%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "11",
    url: "meomeo-1-2",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/06/17/A775_store_1560826012083.png",
    private: true,
    state: "approved",
  },
  {
    id: "WYvpfzsZqaIRUGWH",
    user_id: "A775",
    title: "Storefront2",
    desc: "null",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "22",
    url: "besau",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/06/11/A775_store_1560241358857.png",
    private: true,
    state: "approved",
  },
  {
    id: "xv9xHkni0FHbkuqy",
    user_id: "A775",
    title: "STCIKER",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "stciker",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/06/07/A775_store_1559889792930.png",
    private: false,
    state: "approved",
  },
  {
    id: "qP8aPV7zaV0gfGIV",
    user_id: "A775",
    title: "asfas2242/a",
    desc: "",
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "FjqipWIBiLBkxU3D",
    user_id: "A775",
    title: "MENANA",
    desc: "%3Cp%3Enull%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "MENANA",
    seo_desc:
      "MENANA makes it easier than ever to sell shirts you design, leveraging crowd funding and social media to help you sell your shirt and make money, all with absolutely no money down",
    seo_image_cover:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/06/30/A775_seo_img_vconxnvggdwjq.png",
    fb_pixel: "11",
    url: "menana",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/06/06/A775_store_1559803982616.png",
    private: false,
    state: "approved",
  },
  {
    id: "EUrNm0JN2W41iftO",
    user_id: "A775",
    title: "test t3",
    desc: "%3Cp%3Ebbbbbbbbbbbbbbbbbbb%3C%2Fp%3E",
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "133333324",
    url: "test-t3",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "5fdHcnb4VWPtDNmT",
    user_id: "A775",
    title: "test t1",
    desc: "%3Cp%3Easdsad%3C%2Fp%3E",
    domain_id: "Bnu7jG0jN7JUNwd0",
    domain: "testtestmaipham.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test-t1",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "w74JizSlZuqRdYYQ",
    user_id: "A775",
    title: "Test2105",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "124215125",
    url: "test2105",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "v9QrSzNNent4ZWGE",
    user_id: "A775",
    title: "Store 1",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "store-1-1",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "bfV4dAFRaK1VxNYf",
    user_id: "A775",
    title: "New store April8123",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "new-store-april8123",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "voDDqesj6mnWMrBL",
    user_id: "A775",
    title: "aaa/5",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "5",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/05/17/A775_store_1558088527203.jpg",
    private: true,
    state: "approved",
  },
  {
    id: "1SbwwQFBLG2GEabn",
    user_id: "A775",
    title: "linhdinh",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "3",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/05/20/A775_store_1558325584237.png",
    private: false,
    state: "approved",
  },
  {
    id: "TIiHL4MtnJZtOy1G",
    user_id: "A775",
    title: "aaa/1",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "adOhLgbTf2aS75Uz",
    user_id: "A775",
    title: "sfafafaf",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "aaa2",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "dHAl2P6OOZUsPOmT",
    user_id: "A775",
    title: "sfafafaf",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "2lyp3SEyBZ17D6nj",
    user_id: "A775",
    title: "test 18042019",
    desc: "%3Cp%3Ehihi%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "test18042019",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "ub1pUNEGggyuwtWN",
    user_id: "A775",
    title: "test123",
    desc: "%3Cp%3E123%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "",
    banner: "",
    private: false,
    state: "approved",
  },
  {
    id: "KEG4Twbi7PNeIra3",
    user_id: "A775",
    title: "New storefront 123",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "new-storefront-123",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/05/17/A775_store_1558088646931.jpg",
    private: true,
    state: "approved",
  },
  {
    id: "WkENX8c5gLqn1aPT",
    user_id: "A775",
    title: "New store April8123456",
    desc: "%3Cp%3EHallo%20April123123%3C%2Fp%3E",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "new-store-april8",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/04/07/A775_store_1554695753103.jpg",
    private: true,
    state: "approved",
  },
  {
    id: "HpPkaFvmPNy4ik1V",
    user_id: "A775",
    title: "J26March",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "j26march",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/03/26/A775_store_1553593445434.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "3CvEVbRCZn0g01gc",
    user_id: "A775",
    title: "new store",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "new-store-1",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/03/26/A775_store_1553593392185.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "qYFjgEaOcPabiXMK",
    user_id: "A775",
    title: "2603s1",
    desc: "",
    domain_id: "NONUhEyP1wrpWnvG",
    domain: "tee86.com",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "2603s1",
    banner:
      "https://d1ud88wu9m1k4s.cloudfront.net/isp/2019/03/26/A775_store_1553593441388.jpg",
    private: false,
    state: "approved",
  },
  {
    id: "vxZmGQXoh7luOxHh",
    user_id: "A775",
    title: "Funny T-shirt",
    desc: "%3Cp%3EHigh-qualified%20products.%3C%2Fp%3E",
    domain_id: "jPCsP8jB5tjbYrEE",
    domain: "burgerprints.vn",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    fb_pixel: "",
    url: "funny-t-shirt-11",
    banner: "http://cdn.30usd.com/upload/2019/03/18/store_1552898269531.jpg",
    private: false,
    state: "approved",
  },
];
