export const data = [
  {
    id: "kenTh2Z1UvsE278Q",
    site_name: "Oanh New domain",
    name: "24215s2353.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner:
      "https://dg86kmop4ajn0.cloudfront.net/assets/2021/06/11/A775_uNSyp21pBc1ZKrFaj9EksgEG9_1623383893192.png",
    logo: "https://dg86kmop4ajn0.cloudfront.net/assets/2021/06/11/A775_3UAb0ZANhTHK3t5hlylNCP8lu_1623383929152.png",
    color: "#ed5565",
    create_time: "20190408T214938Z",
    state: "processing",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "anhpham@leadsgen.asia",
      register_name: "test",
      register_street: "test",
      register_postcode: "8200",
      register_city: "Paris",
      register_country_code: "US",
      register_country_name: "France",
    },
  },
  {
    id: "xbAPHB8bO43zDIrb",
    site_name: "trangthanh21",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20190417T050310Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "NsGhXnK1S598SMEX",
    site_name: "test1",
    name: "testaaa1.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20201117T212817Z",
    state: "processing",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "anhpham@leadsgen.asia",
      register_name: "test",
      register_street: "test",
      register_postcode: "8200",
      register_city: "Paris",
      register_country_code: "US",
      register_country_name: "France",
    },
  },
  {
    id: "6cCXLUFoCxRaU64X",
    site_name: "tetet23232",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191204T224958Z",
    state: "processing",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "testmcvn4@gmail.com",
      register_name: "Maison",
      register_street: "42 rue de la Boétie 75009, Paris",
      register_postcode: "8200",
      register_city: "Paris",
      register_country_code: "US",
      register_country_name: "France",
    },
  },
  {
    id: "2zAbr4NBFf6bXaEb",
    site_name: "ghdh",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner:
      "https://dg86kmop4ajn0.cloudfront.net/assets/2021/05/13/A775_J3lw1VSuBCqZOaSGS0aJZjzIk_1620873571253.png",
    logo: "https://dg86kmop4ajn0.cloudfront.net/assets/2021/05/13/A775_ns0b8zqTVUzIzcQzeHw39Q05T_1620873575130.jpg",
    color: "#ed5565",
    create_time: "20191030T004539Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "W9mhA7UWpVF9amzE",
    site_name: "Lam luyen",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191031T051320Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "sLDcXoyiGiewpVb8",
    site_name: "test",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#a0d468",
    create_time: "20190925T222251Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "UblFmi7Zq2QqV0MN",
    site_name: "vostro",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191209T050401Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "ta4I1zVIfJa8kS0p",
    site_name: "dell",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191209T050607Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "FD482Ny0vfU43r5i",
    site_name: "testpm",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20201116T223656Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "1CgeghLrdGPVrW96",
    site_name: "451252152",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20210829T225021Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "wWY7dUdo3qcejJPo",
    site_name: "maimeo",
    name: "maimeo.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191209T050037Z",
    state: "processing",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "mai@leadsgen.asia",
      register_name: "mai pham",
      register_street: "tohuu",
      register_postcode: "100000",
      register_city: "hanoi",
      register_country_code: "US",
      register_country_name: "Vietnam",
    },
  },
  {
    id: "2m1zupdmcfaZUa4J",
    site_name: "fasfsagsa",
    name: "12113vbcd.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20191016T031445Z",
    state: "purchased",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "20210913T040822Z",
    expire_date: "20220913T040822Z",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "anhpham@leadsgen.asia",
      register_name: "Maison test",
      register_street: "test",
      register_postcode: "8200",
      register_city: "Paris",
      register_country_code: "VN",
      register_country_name: "",
    },
  },
  {
    id: "pz6OW9K0E2ACxToN",
    site_name: "112412512",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#ed5565",
    create_time: "20210829T224843Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "LLCiQXEY5I3wT1KF",
    site_name: "BurgerPrints",
    name: "30usd.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "",
    create_time: "20170517T000000Z",
    state: "approved",
    seo_title: "BurgerPrints",
    seo_desc:
      "BurgerPrints makes it easier than ever to sell shirts you design, leveraging crowd funding and social media to help you sell your shirt and make money, all with absolutely no money down",
    seo_image_cover:
      "https://dg86kmop4ajn0.cloudfront.net/assets/2021/07/26/A2075_HdIvTRfS7vHQDeUty5vfiDrLT_1627293678893.jpg",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "ZVqs1yGSZaUVkjlX",
    site_name: "Custom  domain",
    name: "v1.tee86.com",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "",
    color: "#4fc1e9",
    create_time: "20200312T024709Z",
    state: "approved",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "20200312T024600Z",
    expire_date: "20250312T024600Z",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
  {
    id: "3jM9ERCHKriR3fKH",
    site_name: "New domain",
    name: "",
    facebook: "",
    twitter: "",
    instagram: "",
    banner: "",
    logo: "https://dg86kmop4ajn0.cloudfront.net/assets/2022/01/21/A775_kVDlM61BwtsgLNtcqUMZfDpDd_1642754764551.jpg",
    color: "#ec87c0",
    create_time: "20190416T034614Z",
    state: "created",
    seo_title: "",
    seo_desc: "",
    seo_image_cover: "",
    register_date: "",
    expire_date: "",
    active_countdown: false,
    active_auto_discount: false,
    office_address: "",
    tracking_tags: {
      fb_pixel: "",
      gg_adword_id: "",
      gg_analytics_id: "",
      gg_site_verification: "",
      gg_tag_manager_id: "",
      gg_conversion_tracking_id: "",
      tiktok_pixel: "",
    },
    custom_header: "",
    custom_body: "",
    user_id: "A775",
    active_search_bar: false,
    active_customer_login: false,
    gg_account_id: "",
    fb_account_id: "",
    register_info: {
      register_email: "",
      register_name: "",
      register_street: "",
      register_postcode: "",
      register_city: "",
      register_country_code: "",
      register_country_name: "",
    },
  },
];
