export const dataEarning = [
  {
    revenue: 21.99,
    quantity: 1,
    product_id: "WS-CFAJxOx1edtrB",
    discount: 0.00,
    tax: 0.00,
    returns: 28.94,
    product_name: "Kids Tee",
    profit: 4.75,
    product_category: "Custom Apparel",
  },
  {
    revenue: 37.34,
    quantity: 1,
    product_id: "Nhy-R_esvYxrhdCX",
    discount: 0.00,
    tax: 2.40,
    returns: 365.25,
    product_name: "Premium Tee - Unisex",
    profit: 19.90,
    product_category: "Custom Apparel",
  },
  {
    revenue: 53.88,
    quantity: 2,
    product_id: "Av2yevpmUN7rwDp0",
    discount: 0.00,
    tax: 0.00,
    returns: 0.00,
    product_name: "Ceramic Mugs",
    profit: 23.66,
    product_category: "Custom Apparel",
  },
  {
    revenue: 55.88,
    quantity: 2,
    product_id: "j1e2h3Wq4Gz5ksjs",
    discount: 0.00,
    tax: 0.00,
    returns: 64.66,
    product_name: "Ceramic Mugs - Normal",
    profit: 25.56,
    product_category: "Custom Apparel",
  },
  {
    revenue: 83.20,
    quantity: 2,
    product_id: "zUCKpLPrl7xnsQU5",
    discount: 0.00,
    tax: 1.32,
    returns: 1375.15,
    product_name: "Hoodie",
    profit: 26.51,
    product_category: "All Over Prints",
  },
  {
    revenue: 57.88,
    quantity: 2,
    product_id: "tL9HoLtLPWpM1Mz4",
    discount: 0.00,
    tax: 0.00,
    returns: 67.84,
    product_name: "Women's Tee Shirt",
    profit: 28.41,
    product_category: "Custom Apparel",
  },
  {
    revenue: 103.98,
    quantity: 2,
    product_id: "NLpUVKFCzLanQn1I",
    discount: 0.00,
    tax: 0.00,
    returns: 0.00,
    product_name: "Samsung Galaxy Note10 Plus",
    profit: 71.25,
    product_category: "Custom Apparel",
  },
  {
    revenue: 732.93,
    quantity: 25,
    product_id: "-cwc847TMWTaZmVg",
    discount: 0.00,
    tax: 17.88,
    returns: 8322.08,
    product_name: "Popular Tee - Unisex",
    profit: 368.41,
    product_category: "Custom Apparel",
  },
  {
    revenue: 3463.92,
    quantity: 100,
    product_id: "KRfcLkcYItB4MQmG",
    discount: 0.00,
    tax: 181.87,
    returns: 2130.50,
    product_name: "Tee 3D",
    profit: 1343.82,
    product_category: "All Over Prints",
  },
];
